config/routes.rb
Rails.application.routes.draw do
  
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/show'

  post '/validate', :controller=>'patients', :action=>'isallergic'
  resources :hospitals
  resources :requests
  resources :doctors
  get 'homes/index'
  devise_for :users
  resources :users
  root to: 'patients#index'

  get 'notes/index'

  get 'notes/show'

  get 'notes/new'

  get 'notes/edit'
  
  resources :users
  get 'notes/new'

  get 'notes/edit'
  
  resources :patients do
  resources :notes
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/note.rb
class Note < ApplicationRecord
  belongs_to :patient
  
  
  
#  before_create :set_filename
#  after_create :store_file
#  after_destroy :delete_file

 # validates_presence_of :uploaded_file

 # attr_accessor :uploaded_file

#  def link
#    "/uploads/#{CGI.escape(filename)}"
 # end

  #private

  #def store_file
   # File.open(file_storage_location, 'w') do |f|
    #  f.write uploaded_file.read
    #end
 # end

  #def delete_file
   # File.delete(file_storage_location)
  #end

  #def file_storage_location
   # File.join(Rails.root, 'public', 'uploads', filename)
  #end

  #def set_filename
   # self.filename = random_prefix + uploaded_file.original_filename
  #end

  #def random_prefix
   # Digest::SHA1.hexdigest(Time.now.to_s.split(//).sort_by {rand}.join)
  #end
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController

# GET /patients/1/note
  def index
# For URL like /patients/1/notes
# Get the patient with id=1
  @patient = Patient.find(params[:patient_id])
# Access all notes for that patient
  @notes = @patient.notes
end
# GET /patients/1/notes/2
  def show
  @patient = Patient.find(params[:patient_id])
# For URL like /patient/1/notes/2
# Find an note  in patients 1 that has id=2
  @notes = @patient.notes.find(params[:id])
end
# GET /movies/1/reviews/new
  def new
  @patient = Patient.find(params[:patient_id])
# Associate an review object with movie 1
  @note = @patient.notes.build
end
# POST /movies/1/reviews
  def create
  @patient = Patient.find(params[:patient_id])
# For URL like /movies/1/reviews
# Populate an review associate with movie 1 with form data 
# Movie will be associated with the review
#  @review = @movie.reviews.build(params.require(:review).permit!)
  @note = @patient.notes.build(params.require(:note).permit(:details))
  if @note.save
# Save the review successfully
  redirect_to patient_note_url(@patient, @note)
  else
  render :action => "new"
 end
end
# GET /movies/1/reviews/2/edit
  def edit
  @patient = Patient.find(params[:patient_id])
# For URL like /movies/1/reviews/2/edit
# Get review id=2 for movie 1
  @note = @patient.notes.find(params[:id])
end
# PUT /movies/1/reviews/2
  def update
  @patient = Patient.find(params[:patient_id])
  @note = Note.find(params[:id])
  if
  @note.update_attributes(params.require(:note).permit(:details))
# Save the review successfully
  redirect_to patient_note_url(@patient, @note)
 else
  render :action => "edit"
 end
end
# DELETE /movies/1/reviews/2
  def destroy
  @patient = Patient.find(params[:patient_id])
  @note = Note.find(params[:id])
  @note.destroy
  respond_to do |format|
  format.html { redirect_to patient_notes_path(@patient) }
  format.xml { head :ok }
end
end
end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/notes/_form.html.erb
<div class="container">
     <div class="col-sm">
        <div class="card-header">

<%= form_for([@patient, @note]) do |f| %>

<% if @note.errors.any? %>
<div id="error_explanation">
<h2><%= pluralize(@note.errors.count, "error")%>
prohibited this note from being saved:</h2>
<ul>
<% @note.errors.full_messages.each do |msg| %>
<li><%= msg %></li>
<% end %>
</ul>
</div>
<% end %>
<div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :publishdate %>
    <%= f.datetime_field :publishdate %>
  </div>
<div class="area">
<p>
<%= f.label :Details %><br />
<%= f.text_area :details %>
</p>
</div>
<div class="upload">
<p>
<%= f.file_field :uploaded_file %>

</p>
</div>

<div class="actions">
<%= f.submit %> 
<br>
<button ><%= link_to 'Back', patient_notes_path(@patient) %></button>
</div>

<% end %>
</div>
</div></div>

app/views/notes/edit.html.erb
<div vlass="container">
<div class="card">
  <div class="card-body">
  

<h1>Editing Note</h1>
<%= render 'form' %>
<button type="button" class="btn btn-outline-success"> <%= link_to 'Show', patient_note_path(@patient, @note) %></button>
<button type="button" class="btn btn-outline-secondary"><%= link_to 'Back', patient_notes_path(@patient) %> </button>
 

</div></div></div>

app/views/notes/index.html.erb
<br>
<div class="container">
    <div class="card">
  <div class="card-body">
      <div class="col-sm">
        <div class="card-header">

<h1>Records of <%= @patient.name %></h1>
<table>
<tr>
<th>Notes details</th>
</tr>
<% for note in @notes %>
<tr>

<td><%= note.details %></td>
<td>
<button type="button" class="btn btn-outline-info"><%= link_to 'Show', patient_note_path(@patient, note)
%></button></td>
<td> <button type="button" class="btn btn-outline-warning"><%= link_to 'Edit', edit_patient_note_path(@patient, note)
%></button></td>
<td><button type="button" class="btn btn-outline-danger"><%= link_to 'Delete', patient_note_path(@patient, note),
data: { confirm: 'Are you sure?' } %></button></td>
</tr>
<% end %>
</table>
<br />
<button type="button" class="btn btn-primary"><%= link_to 'New note', new_patient_note_path(@patient) %> </button>
<button type="button" class="btn btn-outline-secondary"> <%= link_to 'Back to Patient', @patient %></button>



</div>
</div>
</div>
</div>
</div>

app/views/notes/new.html.erb
<br>
<div class="container">
   
<h1>New Note</h1>
<%= render 'form' %>
</div>

app/views/notes/show.html.erb
<div class="container">
<div class="card">
  <div class="card-body">
      
     <div class="col-sm">
        <div class="card-header">

<p id="notice"><%= notice %></p>

  
<h2> Record of patient: <%= @patient.name%></h2>

 <p> <strong>Name:</strong> <%= @patient.name %> </p>

 <p> <strong>Contact details:</strong> <%= @patient.contact %></p>

 <p> <strong>Date Of Birth:</strong> <%= @patient.date_of_birth %></p>

 <p> <strong>Address:</strong> <%= @patient.address %> </p>

 <p> <strong>Patient Injury:</strong> <%= @patient.injury %> </p>

 <p> <strong>Doctors Action:</strong> <%= @patient.action %> </p>

 <!-- Display the notes of a patient -->
  <div class="card">
  <div class="card-body" >
<h2>Notes</h2>
<% @patient.notes.each do |note| %>


<p>
<b>Note details:</b>
<%= note.details %>
</p>

<% end %>
<button type="button" class="btn btn-outline-warning"><%= link_to 'Edit', edit_patient_path(@patient) %> </button>
<button type="button" class="btn btn-outline-secondary"><%= link_to 'Back', patients_path %> </button>
<button type="button" class="btn btn-outline-success"> <%= link_to 'Show Notes', patient_notes_path(@patient) %></button>


</div></div></div></div></div>
</div></div>