config/routes.rb
Rails.application.routes.draw do
  
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/show'

  post '/validate', :controller=>'patients', :action=>'isallergic'
  resources :hospitals
  resources :requests
  resources :doctors
  get 'homes/index'
  devise_for :users
  resources :users
  root to: 'patients#index'

  get 'notes/index'

  get 'notes/show'

  get 'notes/new'

  get 'notes/edit'
  
  resources :users
  get 'notes/new'

  get 'notes/edit'
  
  resources :patients do
  resources :notes
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/request.rb
class Request < ApplicationRecord
  belongs_to :hospital, :optional => true

  
  validates :request, presence: true
end

app/controllers/requests_controller.rb
class RequestsController < ApplicationController
  before_action :set_request, only: [:show, :edit, :update, :destroy]

  # GET /requests
  # GET /requests.json
  def index
    @requests = Request.all
  end

  # GET /requests/1
  # GET /requests/1.json
  def show
  end

  # GET /requests/new
  def new
    @request = Request.new

  end

  # GET /requests/1/edit
  def edit
  end

  # POST /requests
  # POST /requests.json
  def create
    @request = Request.new(request_params)
    @request.save


    respond_to do |format|
      if @request.save

      format.html { redirect_to @request, notice: 'Record was successfully created.' }
        format.json { render :show, status: :created, location: @request }
      else
        format.html { render :new }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /requests/1
  # PATCH/PUT /requests/1.json
  def update
    respond_to do |format|
      if @request.update(request_params)
        format.html { redirect_to @request, notice: 'Request was successfully updated.' }
        format.json { render :show, status: :ok, location: @request }
      else
        format.html { render :edit }
        format.json { render json: @request.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /requests/1
  # DELETE /requests/1.json
  def destroy
    @request.destroy
    respond_to do |format|
      format.html { redirect_to requests_url, notice: 'Request was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_request
      @request = Request.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def request_params
      params.require(:request).permit(:request, :hospitalname)
    end
end

app/helpers/requests_helper.rb
module RequestsHelper
end

app/views/requests/_form.html.erb
<%= form_with(model: request, local: true) do |form| %>
  <% if request.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(request.errors.count, "error") %> prohibited this request from being saved:</h2>

      <ul>
      <% request.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
   <div class="field">
    <%= form.label :hospital %>
    <%= form.select :hospital_id, options_for_select(Hospital.all.map{|hospital| [hospital.name, hospital.id]}), { :include_blank => true, :prompt => 'Select Hospital'} %>
  </div>
  
  <div class="field">
    <%= form.label :department %>
    <%= form.text_field :department %>
  </div>

  <div class="field">
    <%= form.label :request %>
    <%= form.text_area :request, id: :request_request %>
  </div>
</br>
 
 

  <div class="actions">
    <%= form.submit %>
    <button><%= link_to 'Back', requests_path %> </button>

  </div>
<% end %>

app/views/requests/edit.html.erb
<h1>Editing Request</h1>

<%= render 'form', request: @request %>

<%= link_to 'Show', @request %> |
<%= link_to 'Back', requests_path %>

app/views/requests/index.html.erb
<h1>Requests#index</h1>
<p id="notice"><%= notice %></p>

<table>
  <thead>
    <tr>
     
      <th>Request</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @requests.each do |request| %>
      <tr>
       
        <td><%= request.request %></td>
        
        <td><button type="button" class="btn btn-outline-info"><%= link_to 'Show', request %></button></td>
        <td><button type="button" class="btn btn-outline-warning"><%= link_to 'Edit', edit_request_path(request) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to 'Destroy', request, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<td><button><%= link_to 'New Request', new_request_path %></button></td>
<button><%= link_to 'Back', patients_path %> </button>

app/views/requests/new.html.erb
<br>
<div class="container">
    
    <div class="card">
  <div class="card-body">
      

<h1>New Request</h1>

       <div class="col-sm">
        <div class="card-header">
<%= render 'form', request: @request %>

</div>
</div>
</div>
</div>
</div>

app/views/requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
 
<p>
  <strong>Request:</strong>
  
  <%= @request.request %>
</p>


<button type="button" class="btn btn-outline-warning"><%= link_to 'Edit', edit_request_path(@request) %> </button>
<button type="button" class="btn btn-outline-secondary"><%= link_to 'Back', patients_path %></button>