config/routes.rb
Rails.application.routes.draw do
  
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/show'

  post '/validate', :controller=>'patients', :action=>'isallergic'
  resources :hospitals
  resources :requests
  resources :doctors
  get 'homes/index'
  devise_for :users
  resources :users
  root to: 'patients#index'

  get 'notes/index'

  get 'notes/show'

  get 'notes/new'

  get 'notes/edit'
  
  resources :users
  get 'notes/new'

  get 'notes/edit'
  
  resources :patients do
  resources :notes
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/patient.rb
class Patient < ActiveRecord::Base
validates :name, presence: true,
                    length: { minimum: 5 }

belongs_to :doctor, :optional => true
has_many :notes
has_many :requests

#search box for patients names
  def self.search(search)
    if search.present?
      Patient.where('name LIKE ?', "%#{search}%")
    else
      Patient.all
     
    end
  end    
end

app/controllers/patients_controller.rb
class PatientsController < ApplicationController
  before_action :set_patient, only: [:show, :edit, :update, :destroy]

  # GET /patients
  # GET /patients.json
  def index
    @patients = Patient.all
    @patients = Patient.search(params[:search])
    
   # @q = Patient.ransack(params[:q])
   # @patient = @q.result.includes(:injury)
    
    respond_to do |format|
      format.html
      format.pdf do
        pdf = PatientPdf.new(@patients)
        send_data pdf.render, filename: 'Patients.pdf', type: 'application/pdf', disposition: "inline"
      end
    end
  end
  
  
  

#custom gem try Penicillin -> results antibiotic A
 def isallergic
   @input1 = params[:search_string]
   @result = Check.runcheck(@input1)
   flash[:notice] =@result
   redirect_to request.referrer
 end


  # GET /patients/1
  # GET /patients/1.json
  def show
  end

  # GET /patients/new
  def new
    @patient = Patient.new
  end

  # GET /patients/1/edit
  def edit
  end

  # POST /patients
  # POST /patients.json
  def create
    @patient = Patient.new(patient_params)
	
    respond_to do |format|
      if @patient.save
        format.html { redirect_to @patient, notice: 'Patient was successfully created.' }
        format.json { render :show, status: :created, location: @patient }
      else
        format.html { render :new }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patients/1
  # PATCH/PUT /patients/1.json
  def update
    respond_to do |format|
      if @patient.update(patient_params)
        format.html { redirect_to @patient, notice: 'Patient was successfully updated.' }
        format.json { render :show, status: :ok, location: @patient }
      else
        format.html { render :edit }
        format.json { render json: @patient.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patients/1
  # DELETE /patients/1.json

  
  
  def destroy
    
    @patient.destroy
    respond_to do |format|
      format.html { redirect_to patients_url, notice: 'Patient was successfully deleted.' }
      format.json { head :no_content }
    end
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patient
      @patient = Patient.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patient_params
      params.require(:patient).permit(:name, :contact, :date_of_birth, :address, :injury, :action)
    end
end

app/helpers/patients_helper.rb
module PatientsHelper
end

app/views/patients/_form.html.erb
<div class="container">

<%= form_with(model: patient, local: true) do |form| %>
  <% if patient.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patient.errors.count, "error") %> prohibited this patient from being saved:</h2>

      <ul>
      <% patient.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :patient_name %>
  </div>

  <div class="field">
    <%= form.label :contact %>
    <%= form.text_field :contact, id: :patient_contact %>
  </div>

  <div class="field">
    <%= form.label :date_of_birth %>
    <%= form.date_field :date_of_birth, id: :patient_date_of_birth %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :patient_address %>
  </div>

  <div class="field">
    <%= form.label :injury %>
    <%= form.text_field :injury, id: :patient_injury %>
  </div>

  <div class="field">
    <%= form.label :action %>
    <%= form.text_area :action, id: :patient_action %>
  </div>

  <div class="actions">
    <%= form.submit %>
    <button><%= link_to 'Back', patients_path %></button>
  </div>
<% end %>
</div>

app/views/patients/edit.html.erb
<div class="container"></div>
<div class="card">
  <div class="card-body">
      
       <div class="col-sm">
        <div class="card-header">
<h1>Editing Patient</h1>

<%= render 'form', patient: @patient %>

</div></div></div></div></div>

app/views/patients/index.html.erb
<br>

<div class="container">
    <div class="card">
  <div class="card-body">
      <div class="row">
    <div class="col-sm">  
        <div class="card-header">
         
        
          
<h3>Patients </h3>
<br>

 
<select align= class="form-control form-control-sm">
  <option>Default select</option>
  <option>Alphabetically</option>
  <option>Recent</option>
 
</select>
<!--%= f.label :injury %>-->
      <!--%= f.search_field :injury %>-->

<table>
      <tr>
      <th><font color="navy">Patients Name  </th>
      <th><font color="navy">Contact  </th>
      <th><font color="navy">Date of birth  </th>
      <th><font color="navy">Address</th>
      <th><font color="navy">Injury </th>
      <th><font color="navy">Action </th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patients.each do |patient| %>
      <tr>
        <td><%= patient.name %></td>
        <td><%= patient.contact %></td>
        <td><%= patient.date_of_birth %></td>
        <td><%= patient.address %></td>
        <td><%= patient.injury %></td>
        <td><%= patient.action %></td>
      <td>  <button type="button" class="btn btn-outline-info"><%= link_to 'Show', patient %></button></td>
        <td> <button type="button" class="btn btn-outline-warning"><%= link_to 'Edit', edit_patient_path(patient) %></button></td>
        <td><button type="button" class="btn btn-outline-danger"><%= link_to 'Destroy', patient, method: :delete, data: { confirm: 'Are you sure?' } %></button></td>
      </tr>
    <% end %>

  </tbody>
</table>


<br>

<button type="button" class="btn btn-outline-success"><%= link_to 'New Patient', new_patient_path %></button>

<%= link_to " Download Patients PDF",patients_path(format: 'pdf') %>
<br>

</div></br>
 <div class="row">
    <div class="col-sm">
        <div class="card-header">
          
          
          
<h4>Find Allergy alternatives:</h4>
<%= form_tag "/validate" do %>
<%= text_field_tag :search_string %>
<%= submit_tag "Search" %>



</div><p class="alert alert-secondary"  id="notice"><%= notice %></p></div></div>

<% end %>

</div>
</div>
</div>
<h4 align="center"> Injury's Reports for the week </h4><br>

<%= pie_chart Patient.group(:injury).count %>
<br>
</div>

</div>

app/views/patients/new.html.erb
<div class="container">
    <div class="card">
  <div class="card-body">
      
<h1>New Patient</h1>


       <div class="col-sm">
        <div class="card-header">
<%= render 'form', patient: @patient %>


</div>
</div></div></div></div>

app/views/patients/show.html.erb
<br><div class="card">
  <div class="card-body">
    <div class="alert alert-success" role="alert">
  <p id="notice"><%= notice %></p>
</div>

<h2> Record details of: <%= @patient.name%></h2>

<br>
<p>
  <strong>Name:</strong>
  <%= @patient.name %>
</p>

<p>
  <strong>Contact:</strong>
  <%= @patient.contact %>
</p>

<p>
  <strong>Date of birth:</strong>
  <%= @patient.date_of_birth %>
</p>

<p>
  <strong>Address:</strong>
  <%= @patient.address %>
</p>

<p>
  <strong>Injury:</strong>
  <%= @patient.injury %>
</p>

<p>
  <strong>Action:</strong>
  <%= @patient.action %>
</p>

<button><%= link_to 'Edit', edit_patient_path(@patient) %> </button>
<button><%= link_to 'Back', patients_path %> </button>
<button><%= link_to 'View Requests', requests_path %> </button>
<button><%= link_to'Show Notes', patient_notes_path(@patient) %> </button>
<button><%= link_to 'New Request', new_request_path %></button>


</div></div>