config/routes.rb
Rails.application.routes.draw do
  
  get 'requests/index'
  get 'requests/new'
  get 'requests/edit'
  get 'requests/show'

  post '/validate', :controller=>'patients', :action=>'isallergic'
  resources :hospitals
  resources :requests
  resources :doctors
  get 'homes/index'
  devise_for :users
  resources :users
  root to: 'patients#index'

  get 'notes/index'

  get 'notes/show'

  get 'notes/new'

  get 'notes/edit'
  
  resources :users
  get 'notes/new'

  get 'notes/edit'
  
  resources :patients do
  resources :notes
end
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SmartdoctorApp</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p> 
<div class="container" >
   
    
<nav class="navbar navbar-light" style="background-color: #7aacff;">
     <div class="inner">
  <a class="navbar-brand"  class="nav-collapse" id="nav-collapse" >SmartDoctor</a>

        <%= link_to 'Home |', homes_index_path %> 
        <%= link_to 'Patients |', patients_path %>  
        <%= link_to 'Appointments |', doctors_path %> 
        <%= link_to 'Hospitals', hospitals_path %>
           

<button type="button" class="btn btn-outline-dark" ><%= link_to 'Add Patient', new_patient_path %></button>
<button type="button" class="btn btn-outline-dark"><%= link_to 'Add Appointment', new_doctor_path %></button>
</div>
     

<div>
    <p>
     <%= form_tag patients_path, :method => 'get' do %>
     <p>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search 🔍", :name => nil %>
      
       
     </p>
     
     
 <% end %></div>

  </nav>
  

    <%= yield %>
    </div><br>
    <div align="center">
      <button type="button" class="btn btn-dark"> <%= render "devise/menu/registration_items" %> </button>
<button  type="button" class="btn btn-dark> <%= render 'devise/menu/login_items' %> </button></div>
  </body>
</html>